---
hostname: SW1-St

default_gateway: 172.20.12.17

l2_interfaces:
  - name: "{{ sInt['Fa0/1'] }}"
    description: "Connection to RT1-St"
    trunk:
      native_vlan: 7
      allowed_vlans: 5-6,30,50,60

  - name: "{{ sInt['Fa0/2'] }}"
    description: "Connection to PCD"
    access:
      vlan: 30

  - name: "{{ sInt['Fa0/3'] }}"
    access:
      vlan: 30

  - name: "{{ sInt['Fa0/4'] }}"
    access:
      vlan: 30
  
  - name: "{{ sInt['Fa0/5'] }}"
    access:
      vlan: 30

  - name: "{{ sInt['Fa0/6'] }}"
    access:
      vlan: 30

  - name: "{{ sInt['Fa0/7'] }}"
    access:
      vlan: 30

  - name: "{{ sInt['Fa0/8'] }}"
    access:
      vlan: 30

  - name: "{{ sInt['Fa0/9'] }}"
    access:
      vlan: 30

  - name: "{{ sInt['Fa0/10'] }}"
    access:
      vlan: 30

  - name: "{{ sInt['Fa0/11'] }}"
    access:
      vlan: 30

  - name: "{{ sInt['Fa0/12'] }}"
    access:
      vlan: 30

  - name: "{{ sInt['Fa0/13'] }}"
    access:
      vlan: 30

  - name: "{{ sInt['Fa0/14'] }}"
    access:
      vlan: 30

  - name: "{{ sInt['Fa0/15'] }}"
    access:
      vlan: 30

  - name: "{{ sInt['Fa0/21'] }}"
    description: "Connection to AP1-St"
    trunk:
      native_vlan: 5
      allowed_vlans: 5,50,60

  - name: "{{ sInt['Fa0/22'] }}"
    trunk:
      native_vlan: 5
      allowed_vlans: 5,50,60

svis:
  - vlan_id: 6
    description: "Management Interface"
    ipv4:
      address: 172.20.12.18
      prefix: 29
    ipv6:
      address: "2001:C:0:7::2/64"

unused_interfaces:
  - "{{ sInt['Fa0/16'] }}"
  - "{{ sInt['Fa0/17'] }}"
  - "{{ sInt['Fa0/18'] }}"
  - "{{ sInt['Fa0/19'] }}"
  - "{{ sInt['Fa0/20'] }}"
  - "{{ sInt['Fa0/23'] }}"
  - "{{ sInt['Fa0/24'] }}"
  - "{{ sInt['Gig0/1'] }}"
  - "{{ sInt['Gig0/2'] }}"

trusted_ports:
  - "{{ sInt['Fa0/1'] }}"
  - "{{ sInt['Fa0/2'] }}"
  - "{{ sInt['Fa0/21'] }}"