---
hostname: DHCP-SRV

management_interface:
  - "{{ rInt['Gig0/0'] ~ '.10' }}"
    
dhcp_pools:
  - name: Administration
    network: 
      address: 172.20.3.0
      netmask: 255.255.255.0
    gateway:
      default_router: 172.20.3.1
    excluded:
      start: 172.20.3.0
      end: 172.20.3.5

  - name: Staff
    network: 
      address: 172.20.2.0
      netmask: 255.255.255.0
    gateway:
      default_router: 172.20.2.1
    excluded:
      start: 172.20.2.0
      end: 172.20.2.5
  
  - name: VoIP
    network: 
      address: 172.20.6.0
      netmask: 255.255.255.0
    gateway:
      default_router: 172.20.6.1
    excluded:
      start: 172.20.6.0
      end: 172.20.6.5
  
  - name: Wireless-Zg
    network: 
      address: 172.20.4.0
      netmask: 255.255.254.0
    gateway:
      default_router: 172.20.4.1
    excluded:
      start: 172.20.4.0
      end: 172.20.4.5
  
  - name: Guests-Zg
    network:
      address: 172.20.1.0
      netmask: 255.255.255.0
    gateway:
      default_router: 172.20.1.1
    excluded:
      start: 172.20.1.0
      end: 172.20.1.5

dhcpv6_pools:
  - name: Administration-v6
    prefix: 2001:A::/64
  
  - name: Staff-v6
    prefix: 2001:A:0:1::/64
  
  - name: VoIP-v6
    prefix: 2001:A:0:2::/64
  
  - name: Wireless-Zg-v6
    prefix: 2001:A:0:3::/64
  
  - name: Guests-Zg-v6
    prefix: 2001:A:0:4::/64

subinterfaces:
  - parent: "{{ rInt['Gig0/0'] }}"
    vlan: 10
    description: Subinterface for Vlan 10 - Servers
    ipv4: 
      address: 172.20.0.196
      prefix: 27
    ipv6: 
      address: 2001:A:0:6::4/64
  
  - parent: "{{ rInt['Gig0/0'] }}"
    vlan: 20
    description: Subinterface for Administration Network
    ipv4: 
      address: 172.20.3.5
      prefix: 24
    ipv6: 
      address: 2001:A::5/64
      dhcpv6_pool: Administration-v6

  - parent: "{{ rInt['Gig0/0'] }}"
    vlan: 30
    description: Subinterface for Staff Network
    ipv4: 
      address: 172.20.2.5
      prefix: 24
    ipv6: 
      address: 2001:A:0:1::5/64
      dhcpv6_pool: Staff-v6
  
  - parent: "{{ rInt['Gig0/0'] }}"
    vlan: 40
    description: Subinterface for VoIP Network
    ipv4: 
      address: 172.20.6.5
      prefix: 23
    ipv6: 
      address: 2001:A:0:2::5/64
      dhcpv6_pool: VoIP-v6
  
  - parent: "{{ rInt['Gig0/0'] }}"
    vlan: 50
    description: Subinterface for Wireless Network
    ipv4: 
      address: 172.20.4.5
      prefix: 23
    ipv6: 
      address: 2001:A:0:3::5/64
      dhcpv6_pool: Wireless-Zg-v6
  
  - parent: "{{ rInt['Gig0/0'] }}"
    vlan: 60
    description: Subinterface for Guests Network
    ipv4: 
      address: 172.20.1.5
      prefix: 24
    ipv6: 
      address: 2001:A:0:4::5/64
      dhcpv6_pool: Guests-Zg-v6

static_routes:
  - dest: 0.0.0.0
    prefix: 0
    next_hop: 172.20.0.193
  
  - dest: 172.20.0.192
    prefix: 27
    next_hop: 172.20.0.193
  
  - dest: 172.20.3.0
    prefix: 24
    next_hop: 172.20.3.1
  
  - dest: 172.20.2.0
    prefix: 24
    next_hop: 172.20.2.1
  
  - dest: 172.20.6.0
    prefix: 23
    next_hop: 172.20.6.1
  
  - dest: 172.20.4.0
    prefix: 23
    next_hop: 172.20.4.1
  
  - dest: 172.20.1.0
    prefix: 24
    next_hop: 172.20.1.1
