---
hostname: SW2-Zg

default_gateway: 172.20.0.225

l2_interfaces:
  - name: "{{ sInt['Fa0/1'] }}"
    access:
      vlan: 20
      voice_vlan: 40

  - name: "{{ sInt['Fa0/2'] }}"
    access:
      vlan: 20
      voice_vlan: 40

  - name: "{{ sInt['Fa0/3'] }}"
    access:
      vlan: 20
      voice_vlan: 40

  - name: "{{ sInt['Fa0/4'] }}"
    access:
      vlan: 20
      voice_vlan: 40
  
  - name: "{{ sInt['Fa0/5'] }}"
    access:
      vlan: 20
      voice_vlan: 40

  - name: "{{ sInt['Fa0/6'] }}"
    access:
      vlan: 20
      voice_vlan: 40

  - name: "{{ sInt['Fa0/7'] }}"
    access:
      vlan: 20
      voice_vlan: 40

  - name: "{{ sInt['Fa0/8'] }}"
    access:
      vlan: 20
      voice_vlan: 40

  - name: "{{ sInt['Fa0/9'] }}"
    access:
      vlan: 20
      voice_vlan: 40

  - name: "{{ sInt['Fa0/10'] }}"
    access:
      vlan: 20
      voice_vlan: 40

  - name: "{{ sInt['Fa0/11'] }}"
    access:
      vlan: 30
      voice_vlan: 40

  - name: "{{ sInt['Fa0/12'] }}"
    access:
      vlan: 30
      voice_vlan: 40

  - name: "{{ sInt['Fa0/13'] }}"
    access:
      vlan: 30
      voice_vlan: 40

  - name: "{{ sInt['Fa0/14'] }}"
    access:
      vlan: 30
      voice_vlan: 40

  - name: "{{ sInt['Fa0/15'] }}"
    access:
      vlan: 30
      voice_vlan: 40

  - name: "{{ sInt['Fa0/16'] }}"
    access:
      vlan: 30
      voice_vlan: 40

  - name: "{{ sInt['Fa0/17'] }}"
    access:
      vlan: 30
      voice_vlan: 40

  - name: "{{ sInt['Fa0/18'] }}"
    access:
      vlan: 30
      voice_vlan: 40

  - name: "{{ sInt['Fa0/19'] }}"
    access:
      vlan: 30
      voice_vlan: 40

  - name: "{{ sInt['Fa0/20'] }}"
    description: "Connection to PCB"
    access:
      vlan: 30
      voice_vlan: 40

  - name: "{{ sInt['Fa0/21'] }}"
    description: "Connection to AP1-Zg"
    trunk:
      native_vlan: 5
      allowed_vlans: 5,50,60

  - name: "{{ sInt['Fa0/22'] }}"
    trunk:
      native_vlan: 5
      allowed_vlans: 5,50,60

  - name: "{{ sInt['Fa0/23'] }}"
    description: "Connection to WLC1-Zg"
    trunk:
      native_vlan: 6
      allowed_vlans: 5-6,50,60

  - name: "{{ sInt['Gig0/1'] }}"
    description: "Connection to MLS1-Zg"
    trunk:
      native_vlan: 7
      allowed_vlans: 5-6,10,20,30,40,50,60

  - name: "{{ sInt['Gig0/2'] }}"
    description: "Connection to MLS2-Zg"
    trunk:
      native_vlan: 7
      allowed_vlans: 5-6,10,20,30,40,50,60

svis:
  - vlan_id: 6
    description: "Management Interface"
    ipv4:
      address: 172.20.0.229
      prefix: 27
    ipv6:
      address: "2001:A:0:5::5/64"

unused_interfaces:
  - "{{ sInt['Fa0/24'] }}"
  
trusted_ports:
  - "{{ sInt['Fa0/20'] }}"
  - "{{ sInt['Fa0/21'] }}"
  - "{{ sInt['Fa0/23'] }}"
  - "{{ sInt['Gig0/1'] }}"
  - "{{ sInt['Gig0/2'] }}"