---
vlans: "{{ vlans_internal }}"

sInt_real:
  Fa0/1: FastEthernet0/1
  Fa0/2: FastEthernet0/2
  Fa0/3: FastEthernet0/3
  Fa0/4: FastEthernet0/4
  Fa0/5: FastEthernet0/5
  Fa0/6: FastEthernet0/6
  Fa0/7: FastEthernet0/7
  Fa0/8: FastEthernet0/8
  Fa0/9: FastEthernet0/9
  Fa0/10: FastEthernet0/10
  Fa0/11: FastEthernet0/11
  Fa0/12: FastEthernet0/12
  Fa0/13: FastEthernet0/13
  Fa0/14: FastEthernet0/14
  Fa0/15: FastEthernet0/15
  Fa0/16: FastEthernet0/16
  Fa0/17: FastEthernet0/17
  Fa0/18: FastEthernet0/18
  Fa0/19: FastEthernet0/19
  Fa0/20: FastEthernet0/20
  Fa0/21: FastEthernet0/21
  Fa0/22: FastEthernet0/22
  Fa0/23: FastEthernet0/23
  Fa0/24: FastEthernet0/24
  Gig0/1: GigabitEthernet0/1
  Gig0/2: GigabitEthernet0/2

sInt_pnet:
  Fa0/1: Ethernet0/0
  Fa0/2: Ethernet0/1
  Fa0/3: Ethernet0/2
  Fa0/4: Ethernet0/3
  Fa0/5: Ethernet1/0
  Fa0/6: Ethernet1/1
  Fa0/7: Ethernet1/2
  Fa0/8: Ethernet1/3
  Fa0/9: Ethernet2/0
  Fa0/10: Ethernet2/1
  Fa0/11: Ethernet2/2
  Fa0/12: Ethernet2/3
  Fa0/13: Ethernet3/0
  Fa0/14: Ethernet3/1
  Fa0/15: Ethernet3/2
  Fa0/16: Ethernet3/3
  Fa0/17: Ethernet4/0
  Fa0/18: Ethernet4/1
  Fa0/19: Ethernet4/2
  Fa0/20: Ethernet4/3
  Fa0/21: Ethernet5/0
  Fa0/22: Ethernet5/1
  Fa0/23: Ethernet5/2
  Fa0/24: Ethernet5/3
  Gig0/1: Ethernet6/0
  Gig0/2: Ethernet6/1

sInt: "{{ sInt_real if interface_type == 'real' else sInt_pnet }}"

management_vlan:
  - 6