---
hostname: RT1-St

l3_interfaces:
  - name: "{{ rInt['Gig0/0'] }}"
    description: "Connection to Zagreb"
    ipv4:
      address: 10.0.0.6
      prefix: 30
    ipv6:
      address: "2001:E::2/64"
      link_local: "FE80:0:0:E::2/64"
  
  - name: "{{ rInt['Gig0/1'] }}"
    description: "Connection to Pula"
    ipv4:
      address: 10.0.0.10
      prefix: 30
    ipv6:
      address: "2001:F::2/64"
      link_local: "FE80:0:0:F::2/64"

  - name: "{{ rInt['Gig0/2'] }}"
    description: "Engineering Network"
    ipv4:
      address: 172.20.9.254
      prefix: 24
    ipv6:
      address: "2001:C::1/64"

  - name: Loopback0
    description: "Multimedia Network"
    ipv4: 
      address: 172.20.8.126
      prefix: 26
    ipv6:
      address: "2001:C:0:3::1/64"

  - name: Loopback1
    description: "Design Network"
    ipv4:
      address: 172.20.8.62
      prefix: 26
    ipv6:
      address: "2001:C:0:1::1/64"

  - name: Loopback2
    description: "Communication Network"
    ipv4:
      address: 172.20.8.254
      prefix: 25
    ipv6:
      address: "2001:C:0:2::1/64"

static_routes:
  # Default routes
  - dest: "0.0.0.0"
    prefix: 0
    next_hop: "10.0.0.5"
  
  # Zagreb network
  - dest: "172.20.0.0"
    prefix: 22
    next_hop: "10.0.0.5"
  
  # Pula network
  - dest: "172.20.4.0"
    prefix: 22
    next_hop: "10.0.0.9"

  # Split internal network
  - dest: "172.20.8.0"
    prefix: 22
    next_hop: "172.20.9.254"
