---
hostname: RT1-Pl

l3_interfaces:
  - name: "{{ rInt['Gig0/0'] }}"
    description: "Connection to Zagreb"
    ipv4:
      address: 10.0.0.2
      prefix: 30
    ipv6:
      address: "2001:D::2/64"
      link_local: "FE80:0:0:D::2/64"
  
  - name: "{{ rInt['Gig0/1'] }}"
    description: "Connection to Split"
    ipv4:
      address: 10.0.0.9
      prefix: 30
    ipv6:
      address: "2001:F::1/64"
      link_local: "FE80:0:0:F::1/64"

  - name: "{{ rInt['Gig0/2'] }}"
    description: "Multimedia Network"
    ipv4:
      address: 172.20.4.126
      prefix: 26
    ipv6:
      address: "2001:B:0:3::1/64"

  - name: Loopback0
    description: "Engineering Network"
    ipv4:
      address: 172.20.5.254
      prefix: 24
    ipv6:
      address: "2001:B::1/64"
  
  - name: Loopback1
    description: "Design Network"
    ipv4:
      address: 172.20.4.62
      prefix: 26
    ipv6:
      address: "2001:B:0:1::1/64"
  
  - name: Loopback2
    description: "Communication Network"
    ipv4:
      address: 172.20.4.254
      prefix: 25
    ipv6:
      address: "2001:B:0:2::1/64"

static_routes:
  # Default routes
  - dest: "0.0.0.0"
    prefix: 0
    next_hop: "10.0.0.1"

  # Zagreb network
  - dest: "172.20.0.0"
    prefix: 22
    next_hop: "10.0.0.1"

  # Pula internal network
  - dest: "172.20.4.0"
    prefix: 22
    next_hop: "172.20.4.126"

  # Split network
  - dest: "172.20.8.0"
    prefix: 22
    next_hop: "10.0.0.10"

