---
rInt_real:
  Gig0/0: GigabitEthernet0/0
  Gig0/1: GigabitEthernet0/1
  Gig0/2: GigabitEthernet0/2

rInt_pnet:
  Gig0/0: Ethernet0/0
  Gig0/1: Ethernet0/1
  Gig0/2: Ethernet0/2

rInt: "{{ rInt_real if interface_type == 'real' else rInt_pnet }}"

management_interface:
  - "{{ rInt['Gig0/0'] }}"
