---
- name: Test Pings
  hosts: routers, mls, switches
  gather_facts: no
  
  tasks:
    - name: Test reachability to RT1-Zg (Gig0/0)
      cisco.ios.ios_ping:
        dest: 172.20.0.157
      tags: rt1_zg

    - name: Test reachability to RT1-Zg (Gig0/1)
      cisco.ios.ios_ping:
        dest: 172.20.0.153
      tags: rt1_zg
    
    - name: Test reachability to RT1-Zg (Gig0/2.102)
      cisco.ios.ios_ping:
        dest: 10.0.0.1
      tags: rt1_zg

    - name: Test reachability to RT1-Zg (Gig0/2.103)
      cisco.ios.ios_ping:
        dest: 10.0.0.5
      tags: rt1_zg

    - name: Test reachability to SW1-Zg (Management Interface)
      cisco.ios.ios_ping:
        dest: 172.20.0.228
      tags: sw1_zg

    - name: Test reachability to SW2-Zg (Management Interface)
      cisco.ios.ios_ping:
        dest: 172.20.0.229
      tags: sw2_zg
    
    - name: Test reachability to MLS1-Zg (Gig0/1)
      cisco.ios.ios_ping:
        dest: 172.20.0.158
      tags: mls1_zg

    - name: Test reachability to MLS1-Zg (Vlan5)
      cisco.ios.ios_ping:
        dest: 172.20.0.162
      tags: mls1_zg

    - name: Test reachability to MLS1-Zg (Vlan5)
      cisco.ios.ios_ping:
        dest: 172.20.0.162
      tags: mls1_zg

    - name: Test reachability to MLS1-Zg (Vlan6)
      cisco.ios.ios_ping:
        dest: 172.20.0.226
      tags: mls1_zg

    - name: Test reachability to MLS1-Zg (Vlan10)
      cisco.ios.ios_ping:
        dest: 172.20.0.194
      tags: mls1_zg

    - name: Test reachability to MLS1-Zg (Vlan20)
      cisco.ios.ios_ping:
        dest: 172.20.3.2
      tags: mls1_zg

    - name: Test reachability to MLS1-Zg (Vlan30)
      cisco.ios.ios_ping:
        dest: 172.20.2.2
      tags: mls1_zg

    - name: Test reachability to MLS1-Zg (Vlan40)
      cisco.ios.ios_ping:
        dest: 172.20.6.2
      tags: mls1_zg

    - name: Test reachability to MLS1-Zg (Vlan50)
      cisco.ios.ios_ping:
        dest: 172.20.4.2
      tags: mls1_zg

    - name: Test reachability to MLS1-Zg (Vlan60)
      cisco.ios.ios_ping:
        dest: 172.20.1.2
      tags: mls1_zg

    - name: Test reachability to MLS2-Zg (Gig0/1)
      cisco.ios.ios_ping:
        dest: 172.20.0.154
      tags: mls2_zg

    - name: Test reachability to MLS2-Zg (Vlan5)
      cisco.ios.ios_ping:
        dest: 172.20.0.163
      tags: mls2_zg

    - name: Test reachability to MLS2-Zg (Vlan6)
      cisco.ios.ios_ping:
        dest: 172.20.0.227
      tags: mls2_zg

    - name: Test reachability to MLS2-Zg (Vlan10)
      cisco.ios.ios_ping:
        dest: 172.20.0.195
      tags: mls2_zg

    - name: Test reachability to MLS2-Zg (Vlan20)
      cisco.ios.ios_ping:
        dest: 172.20.3.3
      tags: mls2_zg

    - name: Test reachability to MLS2-Zg (Vlan30)
      cisco.ios.ios_ping:
        dest: 172.20.2.3
      tags: mls2_zg

    - name: Test reachability to MLS2-Zg (Vlan40)
      cisco.ios.ios_ping:
        dest: 172.20.6.3
      tags: mls2_zg

    - name: Test reachability to MLS2-Zg (Vlan50)
      cisco.ios.ios_ping:
        dest: 172.20.4.3
      tags: mls2_zg

    - name: Test reachability to MLS2-Zg (Vlan60)
      cisco.ios.ios_ping:
        dest: 172.20.1.3
      tags: mls2_zg

    - name: Test reachability to SVI5
      cisco.ios.ios_ping:
        dest: 172.20.0.161
      tags: svi

    - name: Test reachability to SVI6
      cisco.ios.ios_ping:
        dest: 172.20.0.225
      tags: svi

    - name: Test reachability to SVI10
      cisco.ios.ios_ping:
        dest: 172.20.0.193
      tags: svi

    - name: Test reachability to SVI20
      cisco.ios.ios_ping:
        dest: 172.20.3.1
      tags: svi

    - name: Test reachability to SVI30
      cisco.ios.ios_ping:
        dest: 172.20.2.1
      tags: svi

    - name: Test reachability to SVI40
      cisco.ios.ios_ping:
        dest: 172.20.6.1
      tags: svi

    - name: Test reachability to SVI50
      cisco.ios.ios_ping:
        dest: 172.20.4.1
      tags: svi

    - name: Test reachability to SVI60
      cisco.ios.ios_ping:
        dest: 172.20.1.1
      tags: svi

    - name: Test reachability to AP1-Zg
      cisco.ios.ios_ping:
        dest: 172.20.0.165
      when: interface_type == "real"
      tags: ap1_zg

    - name: PCA
      cisco.ios.ios_ping:
        dest: 172.20.3.6
      tags: host_zg

    - name: PCB
      cisco.ios.ios_ping:
        dest: 172.20.2.6
      tags: host_zg

    - name: Test reachability to DHCP-SRV
      cisco.ios.ios_ping:
        dest: 172.20.0.196
      tags: dhcp_srv
    
    - name: Test reachability to RT1-Pl (Gig0/1.5)
      cisco.ios.ios_ping:
        dest: 172.20.8.153
      tags: rt1_pl

    - name: Test reachability to RT1-Pl (Gig0/1.6)
      cisco.ios.ios_ping:
        dest: 172.20.8.145
      tags: rt1_pl

    - name: Test reachability to RT1-Pl (Gig0/1.30)
      cisco.ios.ios_ping:
        dest: 172.20.9.1
      tags: rt1_pl

    - name: Test reachability to RT1-Pl (Gig0/1.50)
      cisco.ios.ios_ping:
        dest: 172.20.10.1
      tags: rt1_pl

    - name: Test reachability to RT1-Pl (Gig0/1.60)
      cisco.ios.ios_ping:
        dest: 172.20.8.193
      tags: rt1_pl
    
    - name: Test reachability to RT1-Pl (Gig0/2.102)
      cisco.ios.ios_ping:
        dest: 10.0.0.2
      tags: rt1_pl

    - name: Test reachability to RT1-Pl (Gig0/2.203)
      cisco.ios.ios_ping:
        dest: 10.0.0.9
      tags: rt1_pl

    - name: Test reachability to RT1-Pl (Lo0 Engineering)
      cisco.ios.ios_ping:
        dest: 172.20.11.1
      tags: rt1_pl

    - name: Test reachability to RT1-Pl (Lo1 Design)
      cisco.ios.ios_ping:
        dest: 172.20.8.161
      tags: rt1_pl

    - name: Test reachability to RT1-Pl (Lo2 Communication)
      cisco.ios.ios_ping:
        dest: 172.20.9.129
      tags: rt1_pl

    - name: Test reachability to SW1-Pl (Management Interface)
      cisco.ios.ios_ping:
        dest: 172.20.8.146
      tags: sw1_pl

    - name: PCC
      cisco.ios.ios_ping:
        dest: 172.20.9.6
      tags: host_pl

    - name: Test reachability to AP1-Pl
      cisco.ios.ios_ping:
        dest: 172.20.8.154
      when: interface_type == "real"
      tags: ap1_pl

    - name: Test reachability to RT1-St (Gig0/1.5)
      cisco.ios.ios_ping:
        dest: 172.20.12.25
      tags: rt1_st

    - name: Test reachability to RT1-St (Gig0/1.6)
      cisco.ios.ios_ping:
        dest: 172.20.12.17
      tags: rt1_st

    - name: Test reachability to RT1-St (Gig0/1.30)
      cisco.ios.ios_ping:
        dest: 172.20.13.129
      tags: rt1_st

    - name: Test reachability to RT1-St (Gig0/1.50)
      cisco.ios.ios_ping:
        dest: 172.20.13.1
      tags: rt1_st

    - name: Test reachability to RT1-St (Gig0/1.60)
      cisco.ios.ios_ping:
        dest: 172.20.12.33
      tags: rt1_st
    
    - name: Test reachability to RT1-St (Gig0/2.103)
      cisco.ios.ios_ping:
        dest: 10.0.0.6
      tags: rt1_st

    - name: Test reachability to RT1-St (Gig0/2.203)
      cisco.ios.ios_ping:
        dest: 10.0.0.10

    - name: Test reachability to RT1-St (Lo0 Multimedia)
      cisco.ios.ios_ping:
        dest: 172.20.12.193
      tags: rt1_st

    - name: Test reachability to RT1-St (Lo1 Design)
      cisco.ios.ios_ping:
        dest: 172.20.12.129
      tags: rt1_st

    - name: Test reachability to RT1-St (Lo2 Communication)
      cisco.ios.ios_ping:
        dest: 172.20.12.65
      tags: rt1_st

    - name: Test reachability to SW1-St (Management Interface)
      cisco.ios.ios_ping:
        dest: 172.20.12.18
      tags: sw1_st

    - name: PCD
      cisco.ios.ios_ping:
        dest: 172.20.13.134
      tags: host_st

    - name: Test reachability to AP1-St
      cisco.ios.ios_ping:
        dest: 172.20.12.26
      when: interface_type == "real"
      tags: ap1_st

